baseURL = 'http://it.mbblog.io/'
languageCode = 'en-US'
title = 'it.mbblog.io'
DefaultContentLanguage = "en"
theme = "PaperMod"

enableRobotsTXT = true

# this is needed to allow usage of plain html syntax in markdown files
[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.en]
    disabled = false
    weight = 1
    contentDir = "content"
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    [languages.en.params]
      [languages.en.params.profileMode]
        enabled = true
        title = 'it.mbblog.io'
        subtitle = 'This page is currently under construction'

[params]
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  ShowShareButtons = true
  disableScrollToTop = false
  env = 'production'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 5
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 10
  [[menus.main]]
    name = 'Categories'
    pageRef = '/categories'
    weight = 15
  [[menus.main]]
    name = 'Archive'
    pageRef = '/archives'
    weight = 20